name: Docker Compose Actions

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Images
      run: |
        docker-compose build

    - name: Run Docker Containers
      run: |
        docker-compose up -d

    # Add any additional steps like testing, if necessary

    - name: Shutdown
      run: |
        docker-compose down
